branch-defaults:
  master:
    environment: Highfi-chat-example
    group_suffix: null
environment-defaults:
  Highfi-chat-client:
    branch: null
    repository: null
global:
  application_name: highfi
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
